/**
 * Daftar semua endpoint /api/v1 yang di-proxy dari API pihak ketiga.
 * Nambah endpoint baru = tambah 1 object di sini (+ transformer kecil di
 * /transformers kalau strukturnya beda dari yang lain). Tidak perlu bikin
 * controller atau route baru tiap kali.
 *
 * path         - path publik yang dipanggil konsumen, digabung ke /api/v1
 * upstream.url - URL API pihak ketiga sesungguhnya (jangan pernah dibocorin ke konsumen)
 * paramsMap    - { queryParamPublik: queryParamUpstream }
 * responseType - 'json' (upstream balikin JSON, ditransform) atau 'binary' (gambar/video, di-stream apa adanya)
 * transformer  - nama transformer di /transformers (default dipakai kalau tidak diisi)
 * scope        - scope ApiKey yang wajib dimiliki buat akses endpoint ini
 * cache        - opsional, { ttlSeconds } — cuma untuk responseType 'json'
 */
module.exports = [
  {
    path: '/search/applemusic',
    title: 'Apple Music Search',
    description: 'Search Apple Music for tracks, albums, and artists by keyword.',
    upstream: { url: 'https://api.nexray.eu.cc/search/applemusic', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword' }],
    responseType: 'json',
    scope: 'tools:search',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/search/spotify',
    title: 'Spotify Search',
    description: 'Search Spotify for tracks, albums, and artists by keyword.',
    upstream: { url: 'https://api.nexray.eu.cc/search/spotify', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Laufey' }],
    responseType: 'json',
    scope: 'tools:search',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/search/tiktok',
    title: 'TikTok Video Search',
    description: 'Search TikTok for videos matching a keyword.',
    upstream: { url: 'https://api.nexray.eu.cc/search/tiktok', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Ronaldo' }],
    responseType: 'json',
    scope: 'tools:search',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/search/tiktokphoto',
    title: 'TikTok Photo Search',
    description: 'Search TikTok for photo/slideshow posts matching a keyword.',
    upstream: { url: 'https://api.nexray.eu.cc/search/tiktokphoto', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Nature' }],
    responseType: 'json',
    scope: 'tools:search',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/search/youtube',
    title: 'YouTube Search',
    description: 'Search YouTube for videos matching a keyword.',
    upstream: { url: 'https://api.nexray.eu.cc/search/youtube', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Lemonade' }],
    responseType: 'json',
    scope: 'tools:search',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/maker/brat',
    title: 'Brat Image Maker',
    description: 'Generate a brat-style text image from a short string of text.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/brat', method: 'GET' },
    paramsMap: { text: 'text' },
    paramsInfo: [{ name: 'text', required: true, description: 'Text to render on the image' }],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/bratvid',
    title: 'Brat Video Maker',
    description: 'Generate a brat-style animated video from a short string of text.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/bratvid', method: 'GET' },
    paramsMap: { text: 'text' },
    paramsInfo: [{ name: 'text', required: true, description: 'Text to render in the video' }],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/iqc',
    title: 'Fake Phone Status Bar Maker',
    description: 'Generate a fake phone status bar image with custom carrier, time, and battery level.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/v1/iqc', method: 'GET' },
    paramsMap: { text: 'text', provider: 'provider', jam: 'jam', baterai: 'baterai' },
    paramsInfo: [
      { name: 'text', required: true, description: 'Notification or status text' },
      { name: 'provider', required: true, description: 'Carrier name, e.g. Indosat' },
      { name: 'jam', required: true, description: 'Time to display, e.g. 12:00' },
      { name: 'baterai', required: true, description: 'Battery percentage, e.g. 50' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/fakelobyml',
    title: 'Fake Mobile Legends Lobby Maker',
    description: 'Generate a fake Mobile Legends lobby screenshot with a custom avatar and nickname.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/fakelobyml', method: 'GET' },
    paramsMap: { avatar: 'avatar', nickname: 'nickname' },
    paramsInfo: [
      { name: 'avatar', required: true, description: 'Direct image URL for the avatar' },
      { name: 'nickname', required: true, description: 'In-game nickname to display' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/fakelobyff',
    title: 'Fake Free Fire Lobby Maker',
    description: 'Generate a fake Free Fire lobby screenshot with a custom nickname.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/fakelobyff', method: 'GET' },
    paramsMap: { nickname: 'nickname' },
    paramsInfo: [{ name: 'nickname', required: true, description: 'In-game nickname to display' }],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/fakedana',
    title: 'Fake DANA Balance Maker',
    description: 'Generate a fake DANA e-wallet balance screenshot with a custom amount.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/fakedana', method: 'GET' },
    paramsMap: { nominal: 'nominal' },
    paramsInfo: [{ name: 'nominal', required: true, description: 'Balance amount, e.g. 50000' }],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/fakebank-jago',
    title: 'Fake Bank Jago Balance Maker',
    description: 'Generate a fake Bank Jago balance screenshot with a custom name and amount.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/fakebank-jago', method: 'GET' },
    paramsMap: { nama: 'nama', saldo: 'saldo' },
    paramsInfo: [
      { name: 'nama', required: true, description: 'Account holder name' },
      { name: 'saldo', required: true, description: 'Balance amount, e.g. 100000' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/smeme',
    title: 'Simple Meme Maker',
    description: 'Generate a top/bottom text meme over a custom background image.',
    upstream: { url: 'https://api.nexray.eu.cc/maker/smeme', method: 'GET' },
    paramsMap: { text_atas: 'text_atas', text_bawah: 'text_bawah', background: 'background' },
    paramsInfo: [
      { name: 'text_atas', required: true, description: 'Top text' },
      { name: 'text_bawah', required: true, description: 'Bottom text' },
      { name: 'background', required: true, description: 'Direct image URL for the background' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },

  // ---- Downloader endpoints ----
  {
    path: '/downloader/tiktok',
    title: 'TikTok Downloader',
    description: 'Fetch a downloadable, watermark-free TikTok video/photo from a share link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/tiktok', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'TikTok video/photo share URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/threads',
    title: 'Threads Downloader',
    description: 'Fetch downloadable media from a Threads post link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/threads', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Threads post URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/ytmp3',
    title: 'YouTube to MP3',
    description: 'Convert a YouTube video link to a downloadable MP3 audio file.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/ytmp3', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'YouTube video URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/ytmp4',
    title: 'YouTube to MP4',
    description: 'Convert a YouTube video link to a downloadable MP4 at a chosen resolution.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/ytmp4', method: 'GET' },
    paramsMap: { url: 'url', resolusi: 'resolusi' },
    paramsInfo: [
      { name: 'url', required: true, description: 'YouTube video URL' },
      { name: 'resolusi', required: false, description: 'Resolution, e.g. 360, 720, 1080, 2160' },
    ],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/v1/ytmp4',
    title: 'YouTube to MP4 (v1)',
    description: 'Alternate YouTube-to-MP4 converter endpoint with resolution selection.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/v1/ytmp4', method: 'GET' },
    paramsMap: { url: 'url', resolusi: 'resolusi' },
    paramsInfo: [
      { name: 'url', required: true, description: 'YouTube video URL' },
      { name: 'resolusi', required: false, description: 'Resolution, e.g. 360, 720, 1080' },
    ],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/ytplay',
    title: 'YouTube Play (Search & Download)',
    description: 'Search YouTube by keyword and return a downloadable audio/video result directly.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/ytplay', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Laufey' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/applemusic',
    title: 'Apple Music Downloader',
    description: 'Fetch a downloadable audio preview/track from an Apple Music link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/applemusic', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Apple Music track/album URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/capcut',
    title: 'CapCut Downloader',
    description: 'Fetch a downloadable, watermark-free video from a CapCut template/share link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/capcut', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'CapCut share URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/facebook',
    title: 'Facebook Downloader',
    description: 'Fetch a downloadable video from a public Facebook video link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/facebook', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Facebook video URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/github',
    title: 'GitHub Repo Downloader',
    description: 'Fetch a downloadable zip link and metadata for a public GitHub repository.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/github', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'GitHub repository URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/v1/instagram',
    title: 'Instagram Downloader (v1)',
    description: 'Fetch downloadable media from an Instagram post, reel, or story link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/v1/instagram', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Instagram post/reel URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/v2/instagram',
    title: 'Instagram Downloader (v2)',
    description: 'Alternate Instagram downloader endpoint, useful as a fallback when v1 fails.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/v2/instagram', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Instagram post/reel URL' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/downloader/spotifyplay',
    title: 'Spotify Play (Search & Download)',
    description: 'Search Spotify by keyword and return track metadata plus a downloadable audio link.',
    upstream: { url: 'https://api.nexray.eu.cc/downloader/spotifyplay', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Search keyword, e.g. Laufey' }],
    responseType: 'json',
    scope: 'tools:downloader',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/tools/translate',
    title: 'Text Translator',
    description: 'Translate text into a target language.',
    upstream: { url: 'https://api.nexray.eu.cc/tools/translate', method: 'GET' },
    paramsMap: { text: 'text', lang: 'lang' },
    paramsInfo: [
      { name: 'text', required: true, description: 'Text to translate' },
      { name: 'lang', required: true, description: 'Target language code, e.g. En' },
    ],
    responseType: 'json',
    scope: 'tools:utility',
  },
  {
    path: '/tools/tts-google',
    title: 'Text to Speech (Google)',
    description: 'Convert text into a downloadable spoken-audio file.',
    upstream: { url: 'https://api.nexray.eu.cc/tools/tts-google', method: 'GET' },
    paramsMap: { text: 'text' },
    paramsInfo: [{ name: 'text', required: true, description: 'Text to speak' }],
    responseType: 'binary',
    scope: 'tools:utility',
  },
  {
    path: '/tools/unblur',
    title: 'Image Unblur / Upscale',
    description: 'Sharpen and upscale a blurry image from a direct image URL.',
    upstream: { url: 'https://api.nexray.eu.cc/tools/unblur', method: 'GET' },
    paramsMap: { url: 'url' },
    paramsInfo: [{ name: 'url', required: true, description: 'Direct image URL to unblur' }],
    responseType: 'binary',
    scope: 'tools:utility',
  },
  {
    path: '/ai/glm47flash',
    title: 'GLM-4.7 Flash Chat',
    description: 'Send a prompt to the GLM-4.7 Flash model and get a text completion back.',
    upstream: { url: 'https://api.siputzx.my.id/api/ai/glm47flash', method: 'GET' },
    paramsMap: { prompt: 'prompt', system: 'system', temperature: 'temperature' },
    paramsInfo: [
      { name: 'prompt', required: true, description: 'User prompt' },
      { name: 'system', required: false, description: 'System instruction' },
      { name: 'temperature', required: false, description: 'Sampling temperature, e.g. 0.7' },
    ],
    responseType: 'json',
    scope: 'tools:ai',
  },
  {
    path: '/news/kompas',
    title: 'Kompas News Feed',
    description: 'Fetch the latest headlines from Kompas.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/kompas', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/cnn',
    title: 'CNN Indonesia News Feed',
    description: 'Fetch the latest headlines from CNN Indonesia.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/cnn', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/tribunnews',
    title: 'Tribunnews Feed',
    description: 'Fetch the latest headlines from Tribunnews.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/tribunnews', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/liputan6',
    title: 'Liputan6 Feed',
    description: 'Fetch the latest headlines from Liputan6.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/liputan6', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/sindonews',
    title: 'Sindonews Feed',
    description: 'Fetch the latest headlines from Sindonews.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/sindonews', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/cnbcindonesia',
    title: 'CNBC Indonesia Feed',
    description: 'Fetch the latest headlines from CNBC Indonesia.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/cnbcindonesia', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/news/antara',
    title: 'Antara News Feed',
    description: 'Fetch the latest headlines from Antara News.',
    upstream: { url: 'https://api.siputzx.my.id/api/berita/antara', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:news',
    cache: { ttlSeconds: 300 },
  },
  {
    path: '/info/cuaca',
    title: 'Weather Lookup',
    description: 'Fetch current weather for a location by name.',
    upstream: { url: 'https://api.siputzx.my.id/api/info/cuaca', method: 'GET' },
    paramsMap: { q: 'q' },
    paramsInfo: [{ name: 'q', required: true, description: 'Location name, e.g. pasiran jaya' }],
    responseType: 'json',
    scope: 'tools:info',
    cache: { ttlSeconds: 900 },
  },
  {
    path: '/info/bmkg',
    title: 'BMKG Earthquake Info',
    description: 'Fetch the latest earthquake data from BMKG (Indonesia meteorological agency).',
    upstream: { url: 'https://api.siputzx.my.id/api/info/bmkg', method: 'GET' },
    paramsMap: {},
    paramsInfo: [],
    responseType: 'json',
    scope: 'tools:info',
    cache: { ttlSeconds: 900 },
  },
  {
    path: '/info/jadwaltv',
    title: 'TV Schedule Lookup',
    description: 'Fetch today\'s broadcast schedule for a given Indonesian TV channel.',
    upstream: { url: 'https://api.siputzx.my.id/api/info/jadwaltv', method: 'GET' },
    paramsMap: { channel: 'channel' },
    paramsInfo: [{ name: 'channel', required: true, description: 'Channel name, e.g. sctv' }],
    responseType: 'json',
    scope: 'tools:info',
    cache: { ttlSeconds: 900 },
  },
  {
    path: '/maker/photooxy',
    title: 'PhotoOxy Text Effect',
    description: 'Render text into a PhotoOxy text-effect template image.',
    upstream: { url: 'https://api.siputzx.my.id/api/m/photooxy', method: 'GET' },
    paramsMap: { url: 'url', text1: 'text1' },
    paramsInfo: [
      { name: 'url', required: true, description: 'PhotoOxy template page URL' },
      { name: 'text1', required: true, description: 'Text to render into the effect' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/maker/textpro',
    title: 'TextPro Text Effect',
    description: 'Render text into a TextPro text-effect template image.',
    upstream: { url: 'https://api.siputzx.my.id/api/m/textpro', method: 'GET' },
    paramsMap: { url: 'url', text1: 'text1' },
    paramsInfo: [
      { name: 'url', required: true, description: 'TextPro template page URL' },
      { name: 'text1', required: true, description: 'Text to render into the effect' },
    ],
    responseType: 'binary',
    scope: 'tools:maker',
  },
  {
    path: '/primbon/artinama',
    title: 'Name Meaning Lookup',
    description: 'Fetch the traditional meaning behind a given name.',
    upstream: { url: 'https://api.siputzx.my.id/api/primbon/artinama', method: 'GET' },
    paramsMap: { nama: 'nama' },
    paramsInfo: [{ name: 'nama', required: true, description: 'Name to look up' }],
    responseType: 'json',
    scope: 'tools:primbon',
  },
  {
    path: '/primbon/nomorhoki',
    title: 'Lucky Phone Number Reading',
    description: 'Get a numerology-style reading for a phone number.',
    upstream: { url: 'https://api.siputzx.my.id/api/primbon/nomorhoki', method: 'GET' },
    paramsMap: { phoneNumber: 'phoneNumber' },
    paramsInfo: [{ name: 'phoneNumber', required: true, description: 'Phone number, e.g. 6285658939117' }],
    responseType: 'json',
    scope: 'tools:primbon',
  },
  {
    path: '/primbon/tafsirmimpi',
    title: 'Dream Interpretation',
    description: 'Get a traditional interpretation for a dream keyword.',
    upstream: { url: 'https://api.siputzx.my.id/api/primbon/tafsirmimpi', method: 'GET' },
    paramsMap: { mimpi: 'mimpi' },
    paramsInfo: [{ name: 'mimpi', required: true, description: 'Dream keyword, e.g. bertemu' }],
    responseType: 'json',
    scope: 'tools:primbon',
  },
  {
    path: '/primbon/kecocokan-nama-pasangan',
    title: 'Name Compatibility Reading',
    description: 'Get a traditional compatibility reading between two names.',
    upstream: { url: 'https://api.siputzx.my.id/api/primbon/kecocokan_nama_pasangan', method: 'GET' },
    paramsMap: { nama1: 'nama1', nama2: 'nama2' },
    paramsInfo: [
      { name: 'nama1', required: true, description: 'First name' },
      { name: 'nama2', required: true, description: 'Second name' },
    ],
    responseType: 'json',
    scope: 'tools:primbon',
  },
];
